# Generated by Django 4.1.3 on 2022-11-19 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phrases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('japanese', models.TextField()),
                ('english', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_login', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('japanese', models.TextField()),
                ('english', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WordsFalse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miss_date', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systan.student')),
                ('words', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systan.words')),
            ],
        ),
        migrations.CreateModel(
            name='PhrasesFalse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miss_date', models.DateTimeField(auto_now=True)),
                ('phrases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systan.phrases')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systan.student')),
            ],
        ),
    ]
