# Generated by Django 4.1.3 on 2022-11-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrasesfalse',
            name='state',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wordsfalse',
            name='state',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
