# Generated by Django 3.2.15 on 2022-09-25 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_login', models.DateTimeField(verbose_name='latest login')),
            ],
        ),
        migrations.CreateModel(
            name='TrueOrFalse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrases_False', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systan.phrases')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systan.student')),
                ('words_False', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systan.words')),
            ],
        ),
    ]
