# Generated by Django 3.2.15 on 2022-09-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systan', '0002_student_trueorfalse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='latest_login',
            field=models.DateTimeField(null=True, verbose_name='latest login'),
        ),
    ]
