# Generated by Django 3.2.15 on 2022-09-25 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systan', '0003_alter_student_latest_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trueorfalse',
            name='phrases_False',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systan.phrases'),
        ),
        migrations.AlterField(
            model_name='trueorfalse',
            name='words_False',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systan.words'),
        ),
    ]
