# Generated by Django 3.2.15 on 2022-09-25 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systan', '0004_auto_20220925_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhrasesFalse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systan.phrases')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systan.student')),
            ],
        ),
        migrations.CreateModel(
            name='WordsFalse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systan.student')),
                ('words', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systan.words')),
            ],
        ),
        migrations.DeleteModel(
            name='TrueOrFalse',
        ),
    ]
