# Generated by Django 3.2.15 on 2022-09-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systan', '0005_auto_20220925_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='latest_login',
            field=models.DateTimeField(null=True),
        ),
    ]
