# Generated by Django 3.2.15 on 2022-09-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systan', '0006_alter_student_latest_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='latest_login',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
